### ISSUE TITLE
Loading of GeoNode ressources not possible

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/QGISGeoNodePlugin#268]
**Expected Behavior:**

If I connect to a stable GeoNode version with the QGIS plugin, I will get a list of resources and options to load them (wms/wfs). By clicking wfs, the layer is loaded as a QGIS layer.

**Actual Behaviour:**

The list gets created, but clicking any of the options (wms/wfs) will result in an error:
![grafik](https://github.com/GeoNode/QGISGeoNodePlugin/assets/6172324/5b6e7424-ef7e-48f3-9685-97bd08839ae4)

**Additional Information:**

+ plugin version: 1.0.1
+ QGIS version: 3.34.1-Prizren
+ GeoNode version: 4.2.0.dev0 (current https://stable.demo.geonode.org)

The stacktrace lists an error with `_parse_dataset_detail` function and `raw_dataset.get("metadata_author", {}).get("username", "")`

```
2024-03-06T12:54:02     WARNING    Traceback (most recent call last):
              File "C:\Users/-----/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\geonode_v3.py", line 159, in handle_dataset_detail
              dataset = self._parse_dataset_detail(
              File "C:\Users/-----/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\geonode_v3.py", line 405, in _parse_dataset_detail
              metadata_author=raw_dataset.get("metadata_author", {}).get("username", ""),
             AttributeError: 'list' object has no attribute 'get'
```

**Comment by cedricroy** [comment]
Hi Florian,
Have you solved this issue?
I have the same issue.

**Comment by gannebamm** [comment]
Not yet. We are waiting for funding.

**Comment by gannebamm** [comment]
Update: We will start working on this soon

**Comment by cedricroy** [comment]
great ! thanks for the information

**Comment by vanecat** [comment]
yes please! would love a fix!

**Comment by ahmadzfaiz** [comment]
I'm adding compatibility for GeoNode version 4.2.x in [here](https://github.com/ahmadzfaiz/QGISGeoNodePlugin/releases/tag/geonode). You can using this version while waiting the official release

**Comment by ahmadzfaiz** [comment]
I added compatibility for GeoNode version 4.2.x [here](https://github.com/ahmadzfaiz/QGISGeoNodePlugin/releases/tag/geonode). You can use this version while waiting for the official release.

**Comment by ridoo** [comment]
@giohappy who responsible for this being merged?

**Comment by Gpetrak** [comment]
@ridoo the PR was merged.
