### ISSUE TITLE
WFS cannot be loaded if layer has previously uploaded styles to geonode

### ISSUE THREAD

**Issue by AdamChyl** [GeoNode/QGISGeoNodePlugin#270]
As in the title, if a layer has custom styles loaded from qgis, it is not possible to download this layer again from WFS

buttons disabled after trying to download, layer without styles loads correctly
![Zrzut ekranu 2024-05-22 124915](https://github.com/GeoNode/QGISGeoNodePlugin/assets/149472383/b65f2719-41ac-4134-8082-108e9f8c4e36)

**Comment by AdamChyl** [comment]
Fixed, if styling is done using strings from fields and if these strings contain special characters, it will crash.

Add error ignoring in styles.py file:
# return buffer_.data().decode(encoding=“utf-8”)
return buffer_.data().decode(encoding=“utf-8”, errors=“ignore”)

**Comment by Gpetrak** [comment]
@AdamChyl we made several changes in the way that the plugin handles the style through the WFS. Using the updated code of the plugin (main branch) I cannot re-produce the error. The WFS layer is loaded either with custom or not style. Moreover there is not any crash. Please let us know if the behavior that you described remains the same in the new release.
