### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Gpetrak** [GeoNode/QGISGeoNodePlugin#286]
The following UI improvements are proposed:

- When the user creates a new connection through the plugin, if she/he doesn’t select the “Test Connection” button, but selects just OK, the connection is not created and the plugin raises “invalid connection” error. We have to handle this by: (1) Renaming the “Test connection” button to “Connect” to inform the user that the actual functionality of this button is not to just test the connection, but to create it. (2) Keeping the OK button disabled, until the user select the “Connect” button,

- When the user doesn’t insert the correct URL of a GeoNode instance like https://stable.demo.geonode.org/ but uses other similar and commonly used URLs like: https://stable.demo.geonode.org/geoserver/wms, the plugin raises errors. We have to handle these errors and let the user know that has to correct the URL with a valid one.

- When the user for any reason has an invalid connection with errors and then re-tries to select / create / modify the connection, the previous error is still displayed until the user selects the “Search GeoNode” button. We have to fix this by removing the error when the user selects / corrects the connection.

**Comment by giohappy** [comment]
Did you include all these improvements in #288 @Gpetrak?

**Comment by Gpetrak** [comment]
@giohappy no, this is the issue that I'm working now.

**Comment by Gpetrak** [comment]
The PR for this issue is available [here](https://github.com/GeoNode/QGISGeoNodePlugin/pull/290)
Beyond the reported points above, it is included the fix of `help` button which didn't work, so as to open the QGIS GeoNode plugin's documentation.
It's worth mentioning, that with the current UI, the user cannot save an invalid connection.
